name: Update File List Tree

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-file-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Run tree.js script
      run: node tree.js

    - name: Commit and push if changes
      run: |
        git config --local user.email "743295483@qq.com"
        git config --local user.name "imdreamer2018"
        git add file_list_tree.json
        git commit -m "Update file_list_tree.json" -a || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}